# Generated by Django 2.2.9 on 2020-02-18 08:50

import comp.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comp', '0009_auto_20200218_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to=comp.utils.user_profile_image_path)),
                ('rank', models.IntegerField(default=0)),
                ('phone_number', models.CharField(blank=True, max_length=11)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('gold_list', models.TextField(default='[]')),
                ('silver_list', models.TextField(default='[]')),
                ('bronze_list', models.TextField(default='[]')),
                ('badge_list', models.TextField(default='[]')),
                ('is_id', models.IntegerField(default=0)),
                ('star', models.ManyToManyField(blank=True, to='comp.Comp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
