# Generated by Django 2.2.9 on 2020-02-12 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('rank', models.IntegerField(default=0)),
                ('gold_list', models.TextField(default='[]')),
                ('silver_list', models.TextField(default='[]')),
                ('bronze_list', models.TextField(default='[]')),
                ('badge_list', models.TextField(default='[]')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_id', models.IntegerField(default=0)),
                ('star', models.ManyToManyField(blank=True, to='comp.Comp')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
