# Generated by Django 2.2.9 on 2020-02-11 09:53

import comp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=comp.utils.user_profile_image_path),
        ),
    ]
