# Generated by Django 2.2.9 on 2020-02-18 01:08

import comp.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200213_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=comp.utils.user_profile_image_path),
        ),
    ]
