# Generated by Django 2.2.9 on 2020-02-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_selected',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
    ]
