# Generated by Django 2.2.9 on 2020-02-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_selected',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=1),
        ),
    ]
