# Generated by Django 2.2.9 on 2020-02-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0002_auto_20200205_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comp',
            name='is_main',
        ),
        migrations.AddField(
            model_name='comp',
            name='not_is_main',
            field=models.IntegerField(default=1),
        ),
    ]
