# Generated by Django 2.2.9 on 2020-02-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0002_auto_20200221_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='continue_complete',
            field=models.IntegerField(default=-1),
        ),
    ]
