# Generated by Django 2.2.9 on 2020-02-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0002_auto_20200213_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='timeline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
