# Generated by Django 2.2.9 on 2020-02-17 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comp', '0002_auto_20200213_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='codecomment',
            name='like',
            field=models.ManyToManyField(related_name='codecomment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codepost',
            name='like',
            field=models.ManyToManyField(related_name='codepost_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comcomment',
            name='like',
            field=models.ManyToManyField(related_name='comcomment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comp',
            name='star',
            field=models.ManyToManyField(related_name='comp_star', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compost',
            name='like',
            field=models.ManyToManyField(related_name='compost_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
