# Generated by Django 2.2.9 on 2020-02-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0003_comp_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='prize_context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
