# Generated by Django 2.2.9 on 2020-02-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0003_auto_20200222_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepost',
            name='context_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
