# Generated by Django 2.2.9 on 2020-02-06 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0002_delete_profile'),
        ('comp', '0004_auto_20200205_1814'),
    ]

    operations = [
    ]
