# Generated by Django 2.2.9 on 2020-02-18 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0004_comp_prize_context'),
        ('comp', '0003_auto_20200217_1958'),
    ]

    operations = [
    ]
