# Generated by Django 2.2.9 on 2020-02-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0004_auto_20200205_1814'),
        ('comp', '0002_delete_profile'),
    ]

    operations = [
    ]
