# Generated by Django 2.2.9 on 2020-02-18 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0005_merge_20200218_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='star',
            field=models.ManyToManyField(null=True, related_name='comp_star', to=settings.AUTH_USER_MODEL),
        ),
    ]
