# Generated by Django 2.2.9 on 2020-02-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0006_auto_20200206_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='submit_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
