# Generated by Django 2.2.9 on 2020-02-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0006_auto_20200206_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='comcomment',
            name='is_comment',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ComCommComment',
        ),
    ]
