# Generated by Django 2.2.9 on 2020-02-18 02:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0006_auto_20200218_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='star',
            field=models.ManyToManyField(blank=True, null=True, related_name='comp_star', to=settings.AUTH_USER_MODEL),
        ),
    ]
