# Generated by Django 2.2.9 on 2020-02-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0007_auto_20200218_1118'),
        ('comp', '0006_auto_20200218_1052'),
    ]

    operations = [
    ]
