# Generated by Django 2.2.9 on 2020-02-06 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comp', '0007_auto_20200206_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comcomment',
            name='is_comment',
        ),
        migrations.CreateModel(
            name='ComCommComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('com_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp.ComComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
