# Generated by Django 2.2.9 on 2020-02-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0008_auto_20200206_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comcommcomment',
            old_name='com_comment',
            new_name='comcomment',
        ),
        migrations.RenameField(
            model_name='comcomment',
            old_name='com_post',
            new_name='compost',
        ),
    ]
