# Generated by Django 2.2.9 on 2020-02-18 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0008_merge_20200218_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='comp',
            name='continue_complete',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='codecomment',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='codecomment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='codepost',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='codepost_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comcomment',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='comcomment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comp',
            name='not_is_main',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=1),
        ),
        migrations.AlterField(
            model_name='comp',
            name='star',
            field=models.ManyToManyField(blank=True, null=True, related_name='comp_star', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='compost',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='compost_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_thumb', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('phone', models.CharField(max_length=225)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp.Comp')),
            ],
        ),
    ]
