# Generated by Django 2.2.9 on 2020-02-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0007_answer_submit_count'),
        ('comp', '0006_auto_20200206_0541'),
        ('comp', '0009_auto_20200206_1641'),
    ]

    operations = [
    ]
