# Generated by Django 2.2.9 on 2020-02-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0009_auto_20200218_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comp',
            name='comp_answer',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='comp',
            name='context',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comp',
            name='data_context',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comp',
            name='evaluation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comp',
            name='overview_context',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comp',
            name='prize_context',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comp',
            name='timeline',
            field=models.TextField(),
        ),
    ]
