# Generated by Django 2.2.9 on 2020-02-06 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0010_merge_20200206_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='comp.Comp'),
        ),
    ]
