# Generated by Django 2.2.9 on 2020-02-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0011_auto_20200206_1820'),
        ('comp', '0011_auto_20200206_0919'),
    ]

    operations = [
    ]
