# Generated by Django 2.2.9 on 2020-02-07 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0012_merge_20200207_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='comcomment',
            name='comcommcomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comp.ComComment'),
        ),
        migrations.DeleteModel(
            name='ComCommComment',
        ),
    ]
