# Generated by Django 2.2.9 on 2020-02-07 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0013_auto_20200207_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codepost',
            name='comp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comp.Comp'),
        ),
        migrations.AlterField(
            model_name='codepost',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
