# Generated by Django 2.2.9 on 2020-02-07 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0014_auto_20200207_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comcomment',
            old_name='comcommcomment',
            new_name='comcomment2',
        ),
        migrations.AlterField(
            model_name='codepost',
            name='comp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comp.Comp'),
        ),
        migrations.AlterField(
            model_name='codepost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
