# Generated by Django 2.2.9 on 2020-02-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0015_auto_20200207_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comcomment',
            old_name='comcomment2',
            new_name='commcomment',
        ),
    ]
