# Generated by Django 2.2.9 on 2020-02-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0016_auto_20200207_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comcomment',
            name='commcomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comp.ComComment'),
        ),
    ]
