# Generated by Django 2.2.9 on 2020-02-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0017_auto_20200207_1824'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
