# Generated by Django 2.2.9 on 2020-02-11 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comp', '0018_delete_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comp_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='codecomment',
            old_name='code_post',
            new_name='codepost',
        ),
        migrations.RemoveField(
            model_name='comp',
            name='team_number',
        ),
        migrations.AddField(
            model_name='codecomment',
            name='commcomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comp.CodeComment'),
        ),
        migrations.AddField(
            model_name='comp',
            name='comp_answer',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='FileUp',
        ),
        migrations.AddField(
            model_name='comp_file',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp.Comp'),
        ),
        migrations.AddField(
            model_name='answer',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='comp.Comp'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
